[package]
name = "veri_annotation"
version = "0.1.0"
edition = "2018"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = "0.19.7"
regex = "1"
veri_ir = {path = "../veri_ir"}
veri_engine = {path = "../veri_engine"}

[workspace]
