test compile precise-output
target x86_64

function %amode_reg_reg_imm_shl(i32, i32) -> i64 {
block0(v0: i32, v1: i32):
    v2 = iconst.i32 3
    v3 = iadd v0, v2
    v4 = ishl_imm v1, 3
    v5 = iadd v3, v4
    v6 = load.i64 v5
    return v6
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    3(%rdi,%rsi,8), %rax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq 3(%rdi, %rsi, 8), %rax ; trap: heap_oob
;   movq %rbp, %rsp
;   popq %rbp
;   retq

