[package]
name = "aslp"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.8"
pest_derive = "2.7.8"
enquote = "1.1.0"
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
