[package]
name = "veri-isle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-isle = { path = "../isle/isle" }
rsmt2 = "0.14.1"