name: Rust

on:
  push:
    branches: [ "verify-main" ]
  pull_request:
    branches: [ "verify-main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-rust
    - name: Build
      run: cargo build --verbose -p veri_ir -p veri_engine -p veri_annotation
    - name: Test
      run: cargo test --verbose -p veri_ir -p veri_engine -p veri_annotation
